"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import {
  GraduationCap,
  ArrowLeft,
  Download,
  FileText,
  FileJson,
  Link as LinkIcon,
  Check,
  Copy,
  ExternalLink,
} from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { cn } from "@/lib/utils"
import {
  sampleCoursePlan,
  sampleCourseSettings,
  sampleMaterials,
  sampleCalculusCoursePlan,
} from "@/lib/mock-course-data"
import {
  calculusCourseSettings,
  calculusSampleMaterials,
} from "@/lib/optimizer-data"
import { buildShareUrl } from "@/lib/share-url"
import { setPlanFastForward } from "@/lib/templates"
import type { CourseSettings, CourseMaterial, CoursePlan } from "@/lib/course-types"

type ExportFormat = "markdown" | "canvas" | "link"

interface ExportOption {
  id: ExportFormat
  name: string
  description: string
  icon: React.ReactNode
}

// ---------- Export renderers ----------

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function renderMarkdownSyllabus(
  s: CourseSettings,
  mats: CourseMaterial[],
  plan: CoursePlan
): string {
  const lines: string[] = []
  lines.push(`# ${s.title}`)
  lines.push("")
  const levelLabel =
    s.level === "grad" ? "Graduate" : s.level === "upper-ug" ? "Upper-Undergraduate" : "Introductory"
  lines.push(`**Level:** ${levelLabel}  `)
  lines.push(`**Duration:** ${s.weeks} weeks · ~${s.hoursPerWeek} hrs/week  `)
  if (s.assessmentStyle) lines.push(`**Assessment:** ${s.assessmentStyle}  `)
  if (s.prerequisiteTags.length)
    lines.push(`**Prerequisites:** ${s.prerequisiteTags.join(", ")}  `)
  lines.push("")
  if (s.studentBackground) {
    lines.push("## Expected Student Background")
    lines.push("")
    lines.push(s.studentBackground)
    lines.push("")
  }
  if (s.learningOutcomes) {
    lines.push("## Learning Outcomes")
    lines.push("")
    s.learningOutcomes
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean)
      .forEach((l) => lines.push(`- ${l.replace(/^\d+\.\s*/, "")}`))
    lines.push("")
  }
  if (mats.length) {
    lines.push("## Course Materials")
    lines.push("")
    mats.forEach((m, i) => {
      const tag = m.tag ? ` _(${m.tag})_` : ""
      lines.push(`${i + 1}. **${m.name.replace(/\.pdf$/i, "")}**${tag}`)
      if (m.extractedConcepts && m.extractedConcepts.length > 0) {
        lines.push(`   - Topics: ${m.extractedConcepts.join("; ")}`)
      }
    })
    lines.push("")
  }
  lines.push("## Weekly Schedule")
  lines.push("")
  plan.weeks.forEach((w) => {
    const headline = w.conceptsIntroduced[0] ?? w.inClassFocus.split(".")[0]
    lines.push(`### Week ${w.week} — ${headline}`)
    lines.push("")
    if (w.inClassFocus) {
      lines.push(`_${w.inClassFocus}_`)
      lines.push("")
    }
    if (w.readings.length) {
      lines.push("**Readings:**")
      w.readings.forEach((r) => {
        const pages = r.pageRange ? ` (pp. ${r.pageRange})` : ""
        const sections = r.sectionAnchors?.length
          ? ` — ${r.sectionAnchors.join("; ")}`
          : ""
        lines.push(`- ${r.materialName.replace(/\.pdf$/i, "")}${pages}${sections}`)
      })
      lines.push("")
    }
    if (w.conceptsIntroduced.length) {
      lines.push("**Concepts introduced:** " + w.conceptsIntroduced.join(", "))
      lines.push("")
    }
    if (w.discussionQuestions && w.discussionQuestions.length) {
      lines.push("**Discussion questions:**")
      w.discussionQuestions.forEach((q) => lines.push(`- ${q}`))
      lines.push("")
    }
    if (w.problemSet && w.problemSet.length) {
      lines.push("**Problem set:**")
      w.problemSet.forEach((p) => lines.push(`- ${p}`))
      lines.push("")
    }
  })
  lines.push("---")
  lines.push(
    `_Generated by Course Designer · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}_`
  )
  return lines.join("\n")
}

// Canvas / Common-Cartridge style modules JSON — one module per week with
// reading items, discussion items, and assignment items. This shape can be
// imported by the Canvas Course Import API; tools like canvas-cli or the
// Common Cartridge Importer convert this to .imscc on the way in.
function renderCanvasModulesJson(
  s: CourseSettings,
  mats: CourseMaterial[],
  plan: CoursePlan
): string {
  const matById = new Map(mats.map((m) => [m.id, m]))
  const payload = {
    course: {
      name: s.title,
      course_code: s.title
        .toUpperCase()
        .replace(/[^A-Z0-9]+/g, "")
        .slice(0, 8),
      term: undefined as string | undefined,
      weeks: s.weeks,
      hours_per_week: s.hoursPerWeek,
      level: s.level,
      assessment_style: s.assessmentStyle,
      learning_outcomes: s.learningOutcomes
        .split("\n")
        .map((l) => l.replace(/^\d+\.\s*/, "").trim())
        .filter(Boolean)
        .map((text, i) => ({ id: `outcome_${i + 1}`, description: text })),
    },
    files: mats.map((m) => ({
      id: `file_${m.id}`,
      display_name: m.name,
      content_type: "application/pdf",
      tag: m.tag,
      extracted_concepts: m.extractedConcepts ?? [],
    })),
    modules: plan.weeks.map((w) => {
      const items: Record<string, unknown>[] = []
      let pos = 0
      w.readings.forEach((r) => {
        items.push({
          position: ++pos,
          type: "File",
          title: r.materialName,
          file_id: matById.get(r.materialId) ? `file_${r.materialId}` : null,
          page_range: r.pageRange ?? null,
          section_anchors: r.sectionAnchors ?? [],
        })
      })
      if (w.discussionQuestions && w.discussionQuestions.length > 0) {
        items.push({
          position: ++pos,
          type: "Discussion",
          title: `Week ${w.week} Discussion`,
          message: `Reflect on this week's topic: ${w.conceptsIntroduced[0] ?? w.inClassFocus}`,
          prompts: w.discussionQuestions,
        })
      }
      if (w.problemSet && w.problemSet.length > 0) {
        items.push({
          position: ++pos,
          type: "Assignment",
          title: `Week ${w.week} Problem Set`,
          submission_types: ["online_upload", "online_text_entry"],
          points_possible: 100,
          questions: w.problemSet,
        })
      }
      return {
        id: `module_week_${w.week}`,
        name: `Week ${w.week}: ${w.conceptsIntroduced[0] ?? "Topic"}`,
        position: w.week,
        unlock_at: null,
        require_sequential_progress: false,
        items,
      }
    }),
    outcome_coverage: plan.outcomeCoverage.map((o) => ({
      outcome: o.outcome,
      covered_in_weeks: o.coveredInWeeks,
      covered_by_files: o.coveredByReadings.map((id) => `file_${id}`),
      is_covered: o.isCovered,
    })),
    generator: {
      name: "Course Designer",
      schema: "canvas-modules-v1",
      generated_at: new Date().toISOString(),
    },
  }
  return JSON.stringify(payload, null, 2)
}

const exportOptions: ExportOption[] = [
  {
    id: "markdown",
    name: "Markdown Syllabus",
    description: "Plain text format, easy to edit and version control",
    icon: <FileText className="h-5 w-5" />,
  },
  {
    id: "canvas",
    name: "Canvas Import",
    description: "JSON format for LMS import (Canvas, Blackboard)",
    icon: <FileJson className="h-5 w-5" />,
  },
  {
    id: "link",
    name: "Public Link",
    description: "Share a read-only view of your course plan",
    icon: <LinkIcon className="h-5 w-5" />,
  },
]

export default function ExportPage() {
  const router = useRouter()
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat | null>(null)
  const [isExporting, setIsExporting] = useState(false)
  const [exportComplete, setExportComplete] = useState(false)
  const [shareLink, setShareLink] = useState("")
  const [linkCopied, setLinkCopied] = useState(false)

  // Load whichever course is currently active so the export reflects the
  // user's actual settings + materials, not a hardcoded ML Systems stub.
  const [settings, setSettings] = useState<CourseSettings>(sampleCourseSettings)
  const [materials, setMaterials] = useState<CourseMaterial[]>(sampleMaterials)
  const [plan, setPlan] = useState<CoursePlan>(sampleCoursePlan)

  useEffect(() => {
    const storedSettings = localStorage.getItem("currentCourseSettings")
    const storedMaterials = localStorage.getItem("currentCourseMaterials")
    if (storedSettings) {
      try {
        const s = JSON.parse(storedSettings) as CourseSettings
        setSettings(s)
        const isCalc = (s.title ?? "").toLowerCase().includes("calculus")
        if (isCalc) {
          setPlan(sampleCalculusCoursePlan)
          if (!storedMaterials) setMaterials(calculusSampleMaterials)
        }
      } catch {
        // ignore
      }
    }
    if (storedMaterials) {
      try {
        setMaterials(JSON.parse(storedMaterials) as CourseMaterial[])
      } catch {
        // ignore
      }
    }
  }, [])

  const handleExport = async () => {
    if (!selectedFormat) return

    setIsExporting(true)

    // Simulate export process
    await new Promise((resolve) => setTimeout(resolve, 1500))

    if (selectedFormat === "link") {
      // Real, self-contained share URL — same encoder used by the Share
      // button on /sample and /new/plan. Recipients open the URL and the
      // /share/[slug] page decodes the course state from the fragment.
      setShareLink(buildShareUrl({ v: 1, settings, materials, plan }))
    }

    setIsExporting(false)
    setExportComplete(true)
  }

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareLink)
    setLinkCopied(true)
    setTimeout(() => setLinkCopied(false), 2000)
  }

  const handleDownload = () => {
    const slug = settings.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40) || "course"

    if (selectedFormat === "markdown") {
      const md = renderMarkdownSyllabus(settings, materials, plan)
      triggerDownload(`${slug}-syllabus.md`, md, "text/markdown")
      return
    }

    if (selectedFormat === "canvas") {
      const json = renderCanvasModulesJson(settings, materials, plan)
      triggerDownload(`${slug}-canvas-modules.json`, json, "application/json")
      return
    }
  }

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-40 w-full border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
              <GraduationCap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="font-semibold text-foreground text-lg">Course Designer</span>
          </Link>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              setPlanFastForward()
              router.push("/new/plan")
            }}
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to plan
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 py-8">
        <div className="container mx-auto px-4 max-w-2xl">
          <div className="mb-8">
            <h1 className="text-2xl font-semibold text-foreground mb-2">Export Course Plan</h1>
            <p className="text-muted-foreground">
              Choose a format to export your course plan.
            </p>
          </div>

          {!exportComplete ? (
            <>
              {/* Export Options */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
                {exportOptions.map((option) => (
                  <Card
                    key={option.id}
                    className={cn(
                      "cursor-pointer transition-all hover:shadow-md",
                      selectedFormat === option.id
                        ? "ring-2 ring-primary border-primary"
                        : "border-border"
                    )}
                    onClick={() => setSelectedFormat(option.id)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start gap-3">
                        <div
                          className={cn(
                            "flex items-center justify-center h-10 w-10 rounded-lg border",
                            selectedFormat === option.id
                              ? "bg-primary text-primary-foreground border-primary"
                              : "bg-secondary text-muted-foreground border-border"
                          )}
                        >
                          {option.icon}
                        </div>
                        <div className="flex-1">
                          <p className="text-sm font-medium text-foreground">{option.name}</p>
                          <p className="text-xs text-muted-foreground mt-0.5">
                            {option.description}
                          </p>
                        </div>
                        {selectedFormat === option.id && (
                          <Check className="h-4 w-4 text-primary" />
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>

              {/* Export Button */}
              <div className="flex justify-end">
                <Button
                  size="lg"
                  onClick={handleExport}
                  disabled={!selectedFormat || isExporting}
                  className="min-w-[200px]"
                >
                  {isExporting ? (
                    <>
                      <Download className="mr-2 h-4 w-4 animate-bounce" />
                      Exporting...
                    </>
                  ) : (
                    <>
                      <Download className="mr-2 h-4 w-4" />
                      Export
                    </>
                  )}
                </Button>
              </div>
            </>
          ) : (
            <Card className="border-border">
              <CardHeader className="text-center pb-2">
                <div className="mx-auto mb-4 flex items-center justify-center h-12 w-12 rounded-full bg-accent/10">
                  <Check className="h-6 w-6 text-accent" />
                </div>
                <CardTitle className="text-lg">Export Complete</CardTitle>
                <CardDescription>
                  {selectedFormat === "link"
                    ? "Your shareable link is ready"
                    : "Your file is ready for download"}
                </CardDescription>
              </CardHeader>
              <CardContent className="pt-4">
                {selectedFormat === "link" ? (
                  <div className="space-y-4">
                    <div className="flex gap-2">
                      <Input value={shareLink} readOnly className="font-mono text-sm" />
                      <Button variant="outline" size="icon" onClick={handleCopyLink}>
                        {linkCopied ? (
                          <Check className="h-4 w-4 text-accent" />
                        ) : (
                          <Copy className="h-4 w-4" />
                        )}
                      </Button>
                      <Button variant="outline" size="icon" asChild>
                        <a href={shareLink} target="_blank" rel="noopener noreferrer">
                          <ExternalLink className="h-4 w-4" />
                        </a>
                      </Button>
                    </div>
                    <p className="text-xs text-muted-foreground text-center">
                      Anyone with this link can view your course plan (read-only)
                    </p>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-4">
                    <Button size="lg" onClick={handleDownload}>
                      <Download className="mr-2 h-4 w-4" />
                      Download {selectedFormat === "markdown" ? ".md" : ".json"}
                    </Button>
                    <Button variant="ghost" onClick={() => setExportComplete(false)}>
                      Export another format
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      </main>
    </div>
  )
}
